# lighty configuration file
#
# you can use '{{CWD}}' in any string to subsitute the current working directory

# Path to lighttpd binary - essential that this is correct
lighty: "$LIGHTTPD_PATH"

# Directory from which to serve. Will be prepended with CWD unless there is a leading slash.
document_root: "."

# Setting dispatcher will cause all 404s to be routed to that URL
dispatcher: false

# Are directory listings enabled by default? If not, you need to pass --directory-listing to lighty
directory_listing: false

# Port to listen on
port: 3000

# PHP configuration options
php:
    
    # Is PHP enabled by default? If not, you need to pass --php to lighty
    enabled: false
    
    # Explicity state default version to use
    # By default, lighty will choose the best available version
    #version: 5_2_8
    
    # Specify the available versions of PHP here
    # Values should be paths to *FastCGI* binaries.
    #versions:
    #    5_2_8: "/opt/local/bin/php-cgi"

    # Hash of php.ini directives to be passed to php-cgi via -d CLI option
    #ini:
        